@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

interface Array<E> << interface >> {
  + searchBackward(E): boolean
  + get(int): E
  + insertLast(E): void
  + searchForward(E): boolean
  + insertAt(E, int): void
  + iterator(): Iterator<E>
  + searchIndexOf(E): int
  + size(): int
  + removeAt(int): void
  + removeLast(): void
}
class ArrayClass<E> {
  + ArrayClass(): 
  + ArrayClass(int): 
  - resize(): void
  + searchIndexOf(E): int
  + searchForward(E): boolean
  + iterator(): Iterator<E>
  + insertLast(E): void
  + insertAt(E, int): void
  + searchBackward(E): boolean
  + removeAt(int): void
  + removeLast(): void
  + get(int): E
  + size(): int
}
class ArrayIteratorClass<E> {
  + ArrayIteratorClass(E[], int): 
  + next(): E
  + hasNext(): boolean
}
interface Authored << interface >> {
   author: String
}
class Episode {
  + Episode(String, int, String, String): 
  - releaseDate: String
  + display(): void
   releaseDate: String
}
interface Iterator<E> << interface >> {
  + hasNext(): boolean
  + next(): E
}
interface Languaged << interface >> {
   language: Locale
}
class Main {
  + Main(): 
  - isLanguageValid(String): boolean
  - episodesList(Scanner, Array<Podcasts>): void
  - removeShow(Scanner, Array<Shows>): void
  - getPodcastByTitle(String, Array<Podcasts>): Podcasts?
  - getExistingAuthorName(String, Array<T>): String
  + main(String[]): void
  - removeVideo(Scanner, Array<VideoStructure>, Array<Shows>): void
  - getPodcastByAuthor(String, Array<Podcasts>): Array<Podcasts>
  - commandInterpreter(Scanner, Array<VideoStructure>, Array<Podcasts>, Array<Shows>): void
  - subtitleList(Scanner, Array<VideoStructure>): void
  - createshow(Scanner, Array<VideoStructure>, Array<Shows>): void
  - addSub(Scanner, Array<VideoStructure>): void
  - getVideo(Scanner, Array<VideoStructure>): void
  - idAlreadyExists(String, Array<VideoStructure>): boolean
  - removePodcast(Scanner, Array<VideoStructure>, Array<Podcasts>): void
  - addEpisode(Scanner, Array<VideoStructure>, Array<Podcasts>): void
  - getVideoById(String, Array<VideoStructure>): VideoStructure?
  - titleAlreadyExist(String, Array<Podcasts>): boolean
  - help(): void
  - addPublishable(Scanner, Array<VideoStructure>): void
  - addPodcast(Scanner, Array<Podcasts>): void
  - getPodcast(Scanner, Array<Podcasts>): void
  - addPremium(Scanner, Array<VideoStructure>): void
  - getShow(Scanner, Array<Shows>): void
  - podcastList(Scanner, Array<Podcasts>): void
}
class Podcasts {
  + Podcasts(String, String, String): 
  - episode: Array<Episode>
  - title: String
  - author: String
  - language: Locale
  + addEpisode(Episode): void
   language: Locale
   episode: Array<Episode>
   title: String
   author: String
}
class PremiumVideos {
  + PremiumVideos(String, int, String, String, String, String, String, String): 
  - subtitles: Array<Subtitles>
  + addSubtitle(String, String): void
  + display(): void
   subtitles: Array<Subtitles>
}
class PublishableVideos {
  + PublishableVideos(String, int, String, String, String, String): 
  - title: String
  - publisher: String
  - language: Locale
  + display(): void
   language: Locale
   publisher: String
   title: String
}
class Shows {
  + Shows(String, PublishableVideos, String): 
  - transmissionDate: String
  - author: String
  + getvideo(): PublishableVideos
   author: String
   title: String
   transmissionDate: String
}
class Subtitles {
  + Subtitles(String, String): 
  - url: String
  - language: Locale
   language: Locale
   url: String
}
interface Titled << interface >> {
   title: String
}
class VideoStructure {
  + VideoStructure(String, int, String): 
  - duration: int
  - id: String
  - url: String
  + display(): void
   duration: int
   id: String
   url: String
}

ArrayClass          -[#008200,dashed]-^  Array              
ArrayClass          -[#595959,dashed]->  ArrayIteratorClass : "«create»"
ArrayIteratorClass  -[#008200,dashed]-^  Iterator           
Episode             -[#000082,plain]-^  VideoStructure     
Main                -[#595959,dashed]->  ArrayClass         : "«create»"
Main                -[#595959,dashed]->  Episode            : "«create»"
Main                -[#595959,dashed]->  Podcasts           : "«create»"
Main                -[#595959,dashed]->  PremiumVideos      : "«create»"
Main                -[#595959,dashed]->  PublishableVideos  : "«create»"
Main                -[#595959,dashed]->  Shows              : "«create»"
Podcasts           "1" *-[#595959,plain]-> "episode\n1" Array              
Podcasts            -[#595959,dashed]->  ArrayClass         : "«create»"
Podcasts            -[#008200,dashed]-^  Authored           
Podcasts            -[#008200,dashed]-^  Languaged          
Podcasts            -[#008200,dashed]-^  Titled             
PremiumVideos      "1" *-[#595959,plain]-> "subtitles\n1" Array              
PremiumVideos       -[#595959,dashed]->  ArrayClass         : "«create»"
PremiumVideos       -[#000082,plain]-^  PublishableVideos  
PremiumVideos       -[#595959,dashed]->  Subtitles          : "«create»"
PublishableVideos   -[#008200,dashed]-^  Languaged          
PublishableVideos   -[#008200,dashed]-^  Titled             
PublishableVideos   -[#000082,plain]-^  VideoStructure     
Shows               -[#008200,dashed]-^  Authored           
Shows              "1" *-[#595959,plain]-> "video\n1" PublishableVideos  
Shows               -[#008200,dashed]-^  Titled             
@enduml
